### ISSUE TITLE
SORSE user name

### ISSUE THREAD

**Issue by sdruskat** [SORSE/Bjornolf-GM-Discord-Bot#1]
Hi @SORSE 

The international Research Software Engineering community is currently setting up a series of online events to replace in-person community events during the Corona crisis. It is called SORSE - Series of Online Research Software Events. We were planning to run a website on GitHub Pages, and in the process of setting up the GitHub organization have realized that the user name is already taken.

Would there be any chance that you agreed to change your user name to something else, so that it is freed up for us to use? I consider asking only because the impact of changing your user name seems to be low at this time, as you seem to have one repository only which hasn't seen a lot of commits lately.

Please let us know if this would be okay for you by just replying here.

Many thanks & best wishes
Stephan

**Comment by JSorse** [comment]
Of course. 
I would be more than happy to do so for you Stephan.
I will update it immediately.

Keep up the great work.

**Comment by sdruskat** [comment]
Sweet, thanks VERY much, @JSorse :).

**Comment by sdruskat** [comment]
And if you're interested, please feel free to join one of the events, they're free of charge. Thanks again!

**Comment by JSorse** [comment]
I will look into it. You are very welcome. :)
